/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AssessRouteImport } from './routes/assess'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CareIndexRouteImport } from './routes/care.index'
import { Route as CareIdRouteImport } from './routes/care.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessRoute = AssessRouteImport.update({
  id: '/assess',
  path: '/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareIndexRoute = CareIndexRouteImport.update({
  id: '/care/',
  path: '/care/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareIdRoute = CareIdRouteImport.update({
  id: '/care/$id',
  path: '/care/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/care/$id': typeof CareIdRoute
  '/care/': typeof CareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/care/$id': typeof CareIdRoute
  '/care': typeof CareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assess': typeof AssessRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/results': typeof ResultsRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/care/$id': typeof CareIdRoute
  '/care/': typeof CareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assess'
    | '/home'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/settings'
    | '/terms'
    | '/care/$id'
    | '/care/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assess'
    | '/home'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/settings'
    | '/terms'
    | '/care/$id'
    | '/care'
  id:
    | '__root__'
    | '/'
    | '/assess'
    | '/home'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/results'
    | '/settings'
    | '/terms'
    | '/care/$id'
    | '/care/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessRoute: typeof AssessRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResultsRoute: typeof ResultsRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  CareIdRoute: typeof CareIdRoute
  CareIndexRoute: typeof CareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess': {
      id: '/assess'
      path: '/assess'
      fullPath: '/assess'
      preLoaderRoute: typeof AssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/': {
      id: '/care/'
      path: '/care'
      fullPath: '/care/'
      preLoaderRoute: typeof CareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care/$id': {
      id: '/care/$id'
      path: '/care/$id'
      fullPath: '/care/$id'
      preLoaderRoute: typeof CareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessRoute: AssessRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResultsRoute: ResultsRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  CareIdRoute: CareIdRoute,
  CareIndexRoute: CareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
